# Generated by Django 4.2.20 on 2025-04-02 16:05

from django.db import migrations, models
import reviews.validations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='titles',
            name='rating',
        ),
        migrations.AlterField(
            model_name='titles',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='titles',
            name='year',
            field=models.IntegerField(help_text='Год выпуска не позднее текущего', validators=[reviews.validations.validations_year], verbose_name='Год'),
        ),
    ]
